GET http://localhost:8000/exercises?page=1&limit=10
Content-Type: application/json

###

GET http://localhost:8000/exercises?programID=2
Content-Type: application/json

###

GET http://localhost:8000/exercises?search=5
Content-Type: application/json

###

GET http://localhost:8000/exercises
Content-Type: application/json

###

POST http://localhost:8000/exercises
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIzIiwiaWF0IjoxNjU4NDc3OTE2NzY1LCJleHAiOjE2NTg0NzgwMDMxNjV9.JJPfRoG28huRbdVXUJR83uFXWUerFagsIc38WV_VwAzNVZJJgB1owvPOOA3006Z_kt7NugVbwKmWa9O58Se5VVT0NZqI_TbEQX01L87U5PsyewZXaUC4UdunGSzjh_kPwhLAWofskwu8g59ExBtinG-YaBeumGNnGu29QnnvtK259N0gqDULouSrJ028oaFUaE1vVZOz1hahC5UFct-RowO7KquO4QkFeXbqJXIWaSSNsNg_EctlwKT1wWfWaxYqX0m2WJzmYoUE6JIyLDEBwPGMpw9npvPnsnhhiSy52NOMRv1K7NXkypJFP53x8gvntD5Pwd8a1eZBskqNnaTOFGnPCBsuNPKUfToeRdW6h0ioaf2kM5VnY-lbJovZnph827F1PdgTQhI5UieV7MxfJ8KaloUI-cbd05NrktP-7vSQK8bbEh6QLshbGzKPV__pCF9EHpPj81SJC1Z391yrHgLJXsxwNQ3sKIBQkWstcUQlT5f-VieUb8lBbd2qtvhdP0nZ1Ib06UaFtKrqFlAd2UOCxq_C2MTCEWDXFmrZKSSPbbH0aRaR5HMoRNL4kPJRg2HomAR1X4wn2LRe87HdIxgB9ahv26-HdVjAS7sEzMB-m1sqxdf6W2ojrhgV2J2oU0jACuJsjuScHCLz8tfu-u8zSCNfy_-4vC6Q5IkcIbY
Content-Type: application/json

{
    "difficulty": "EASY",
    "name": "Exercise 39",
    "programID": 1
}

###

PUT http://localhost:8000/exercises/11
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIzIiwiaWF0IjoxNjU4NDExMzY3NjA2LCJleHAiOjE2NTg0MTE0NTQwMDZ9.P4yN48_F6U6YuBaMTATEcNCYiVKNopuA7U6ZMCAsXJjbWRPVVzWuWaYTv1DRL1dc_N81k9c1Tu0yiGE7AMotuBympRQSh-6FKeuvtPj0U0JPc0Qa98ZF8WDg4XTifHK22EeE6_bpKnVUorWMUy30ghRZRg5kKIqA1RHhHNlJPxO7i28UOHtNhhebWHNegAgR2deRmqXD3zrDEAHZ0PQ0HaC-hrnud9uu7Zs6gGaNNsEQyQQYqX934sB5A-Gp1PLLSpKLyLIji_c6BP7ghEImVZIUUOagRfwUxHRmT_kNC_VaBk8uL7kWXe3KiL3vQIyHMeQW_UCQQUJSUk7dLLLNC4jRZnsnvrpxDfS7LZ3R6ui5BUjXiwwptCUM4lD5XCnqaFvlHl1fJuiX0s_jjVV2E9OP-o-my38fQ5SRlin8SNg6xS-YwnCmB0sGYsrsIYkgWieIcTX7DhAqGDKQ4Qso66FPy5JhJBjCL0M6EOhfDLQ3xkQIjDS13wXEDpZFfPDHDB6siGMvWvNflF1J3bXqq7R5hKoofbf-Yn606Jw551L7Iv2FIYWLmV4SuCnjSkCXxKh5FMWJc-qQK3FikEORrp4rt8v9ThP2Rqjvmy3QGIAuHoGAvrbdZOipUHl60oBfjcts5xXnr0HlAdeK7vqzVBU5o3wwMte-DhSo8tprJEo
Content-Type: application/json

{
    "difficulty": "HARD",
    "name": "skakanie",
    "programID": 1
}

###

DELETE http://localhost:8000/exercises/9
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIzIiwiaWF0IjoxNjU4NDExNzUxODAzLCJleHAiOjE2NTg0MTE4MzgyMDN9.KtNv5ro8ZLBNyRjIvQFQ0s5EO7Zl1knDVxJrgnvuiMnCLXz48e0iWJye9TvngrjCnCJdrqHcXgpRBNKvpPxt_k2HvEaSxjkxh_Xz5XB-GdHbYAqMLNdbgNvpOD3v-dGarkDaUPvVD-9mCpNLb0gKD-k0ioFoczRNxWwuh1YfpGN-mwsu_Ikq3TpNeMzSPSjo16w0E78PQj7NZTPBM0W9Snfk2WW4G3bOldJ4miXZEbaSkXztHwuyk6VMjwC8nn9JVZt_jLECEafZvNJ51kDZ2XeLspCMNE6y8ZUkhOHWyZlefTyDw0wRzePz3zZyYMkFlXrVY1fpXolV9Zf-ivdWJXwMjO_CTaD0xdKaYLKhoeiYG-EH94NRNMlfx50CNFmHdvps8tPddX5e2PZha9MQh-5rebB_lza0HObqGK585nADgu8jVMegILg1jwgLT74eq8UC0jhdFSO_oPe7Bmec2B9fj8p-JIZLWPGYkGNfQhU2GXGzwNPYWIXyavy4u0ENHncDU4nsgwH5CeD-6K_WHINl0gmvsPUcdvUnhI19Kc3L-a9IdBJ5l0mU0dcQUd6EonH-AcciO8CRd1xl8Ha26A2QKiepA1aIA6DB_ZVbVAhl8g3B8E5pK39lJa-igTRFEzhhVp_ijtdlvNF9JaXtAR2edavKsdUQyGnvfOtTPcQ
