GET http://localhost:8000/history
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIzIiwiaWF0IjoxNjU4ODMzMDkxMTc5LCJleHAiOjE2NTg4MzMxNzc1Nzl9.n9UzbrzfcwNlZ8mibl9mm5f5aj0PQmjHuenw1ohaaOtgD6gmYLGUJJzXvzOzl5ZGwiHYPE0-ORub5RIsD0WXAgNOcSqRJeZfPmBegskY2IncjMIffU00tKo1J4Ao7HDDtAF3aDqKHwFyrZy280dlzkKFWLmE-zFqvQfU-O-DVleRNtzN9Z8b5x6lZx4mCb12-9tg-h7JeRZQkL5wZdcPoDr4nLJRZy0ISrKM0p0a3POsaDrXQS7GfLoNRx6BEWISipZFoy566Uqtsko9nO5TnM5ZIO9zN7KF91233dF9DQwFFTIWlJKXt2xCb8xq7TKvzqqKD-D1bWgooFe975TTYPEgpdM9NDoWRdAn0OlKnbGKt-D_DLMb2M0WMB6Yn-jiCSuiBRJVl65CH1BSVd9KXyDEKOa-AhEMWQ9W41xlii_BtawG2ORLT6Ik4pAR71NEgeir1w3F32kNl8QzjI40mfhoG3zPKltk2H6nyTCg3sMn3gMzRB2PzU5-WJOGGvTL-lFMNZQRodpHaTGXxlq4t0a3jW6E2n0YoQzEyCk2uLxP7U5fNTiGVQNIlQkQWtkVDEvwKdZS5C4NPwfptHKbhyDfB97cjPFW5YFLgKXex9966AR6I0Iwbb1EJk9wfq7ej9gFTIRvBBc-enX1qUhWmsV-n6P5CPy8mTn1r8XQX60

###

GET http://localhost:8000/history/dates
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxIiwiaWF0IjoxNjY0MzkyNzk1MzU1LCJleHAiOjE2NjQzOTI4ODE3NTV9.IY63sVkOHq6iQhtz5_CIlvQm9g7BQzns8iu3jrzitR7ggB-spLcwhmizslhXg45U861Z5KT33oVqlMcV-Ez1MVfHqLq0QolPWS3mRD3_m4kI6jBzKE6kjPJot6shgW1jQcXjbYsHclmRe2cHhnGeoE0djxwAXTnHUdpDw28RMCVI0pZoMUQKFnCwQHYs_S2B5O6ncPUpKeAVE7srz-MvagqTzuuWxGn78mZ3BU7AST4kxvs5Yr4gmz2yK9joDy7aZ0j8zhj7UWpyZ_RDIKrxBVOPuFY8aS8y6W_n4tVHTyuITlEJDrgLDKrpzesFinjHzBH2RC8UU4dN7pOrICJ0dak91FSf0Lxm3O9h2mVUKRXuUuNQO-eXmIj685Db3jtgDgJLk4ZV557Vw_sPWuNSZllGlXpFi8-3AL4Jjin4347iRcis8P0GQ94r3dDL_sgUjY9HDdJQtaWTOJyRSSycrDHhxfHXW8hjoRKtY5DHS334k8SABFoOFZw8g-9LoG6v5m6U3gppGLMO2xFRpEBu_CJIHFrNd2GGpwIXHWxxgOe7c6A8gXR_prZZR_rPShsVv-Fb_Ra7zx0HAzc6KqKU2Z9BjY_KA-dU7ojXgTGqkNQ4NocuuZsTzJkJDZWwh5Bqb-mxI9hfK9mr4HjmGkiPA50moxhzkqEVycGOOJr8T50

###

GET http://localhost:8000/history/2022-08-29
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxIiwiaWF0IjoxNjY0MzkyNzk1MzU1LCJleHAiOjE2NjQzOTI4ODE3NTV9.IY63sVkOHq6iQhtz5_CIlvQm9g7BQzns8iu3jrzitR7ggB-spLcwhmizslhXg45U861Z5KT33oVqlMcV-Ez1MVfHqLq0QolPWS3mRD3_m4kI6jBzKE6kjPJot6shgW1jQcXjbYsHclmRe2cHhnGeoE0djxwAXTnHUdpDw28RMCVI0pZoMUQKFnCwQHYs_S2B5O6ncPUpKeAVE7srz-MvagqTzuuWxGn78mZ3BU7AST4kxvs5Yr4gmz2yK9joDy7aZ0j8zhj7UWpyZ_RDIKrxBVOPuFY8aS8y6W_n4tVHTyuITlEJDrgLDKrpzesFinjHzBH2RC8UU4dN7pOrICJ0dak91FSf0Lxm3O9h2mVUKRXuUuNQO-eXmIj685Db3jtgDgJLk4ZV557Vw_sPWuNSZllGlXpFi8-3AL4Jjin4347iRcis8P0GQ94r3dDL_sgUjY9HDdJQtaWTOJyRSSycrDHhxfHXW8hjoRKtY5DHS334k8SABFoOFZw8g-9LoG6v5m6U3gppGLMO2xFRpEBu_CJIHFrNd2GGpwIXHWxxgOe7c6A8gXR_prZZR_rPShsVv-Fb_Ra7zx0HAzc6KqKU2Z9BjY_KA-dU7ojXgTGqkNQ4NocuuZsTzJkJDZWwh5Bqb-mxI9hfK9mr4HjmGkiPA50moxhzkqEVycGOOJr8T50

###

POST http://localhost:8000/history
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIzIiwiaWF0IjoxNjU4ODMzMDkxMTc5LCJleHAiOjE2NTg4MzMxNzc1Nzl9.n9UzbrzfcwNlZ8mibl9mm5f5aj0PQmjHuenw1ohaaOtgD6gmYLGUJJzXvzOzl5ZGwiHYPE0-ORub5RIsD0WXAgNOcSqRJeZfPmBegskY2IncjMIffU00tKo1J4Ao7HDDtAF3aDqKHwFyrZy280dlzkKFWLmE-zFqvQfU-O-DVleRNtzN9Z8b5x6lZx4mCb12-9tg-h7JeRZQkL5wZdcPoDr4nLJRZy0ISrKM0p0a3POsaDrXQS7GfLoNRx6BEWISipZFoy566Uqtsko9nO5TnM5ZIO9zN7KF91233dF9DQwFFTIWlJKXt2xCb8xq7TKvzqqKD-D1bWgooFe975TTYPEgpdM9NDoWRdAn0OlKnbGKt-D_DLMb2M0WMB6Yn-jiCSuiBRJVl65CH1BSVd9KXyDEKOa-AhEMWQ9W41xlii_BtawG2ORLT6Ik4pAR71NEgeir1w3F32kNl8QzjI40mfhoG3zPKltk2H6nyTCg3sMn3gMzRB2PzU5-WJOGGvTL-lFMNZQRodpHaTGXxlq4t0a3jW6E2n0YoQzEyCk2uLxP7U5fNTiGVQNIlQkQWtkVDEvwKdZS5C4NPwfptHKbhyDfB97cjPFW5YFLgKXex9966AR6I0Iwbb1EJk9wfq7ej9gFTIRvBBc-enX1qUhWmsV-n6P5CPy8mTn1r8XQX60
Content-Type: application/json

{
    "weight": 2,
    "reps": 3,
    "exerciseName": "a",
    "exerciseId": 1,
}

###

DELETE http://localhost:8000/history/3
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIzIiwiaWF0IjoxNjU4NDM1NDU0MjE0LCJleHAiOjE2NTg0MzU1NDA2MTR9.qGNFTpcDJTtoglSZORZ60klx2BLlcuhv-0v5De8_nFMINLnerupT7-v7SNqgFmQO524kusgp-adl_d8y2iqjZn61Fw3hpvKH92cwe--x0oQ8Z4kZm6YgiaETmV6eU1IypR8M1GSLIFDPfT7N7ZimQyTL1twZxQbomvk-CF8ByGjeEjgjSA4MtQWvRdiFSvQK58zj8-k1a1LgwaNI_D1c-zwdcWi88c8j4LIsBqaUuFgarQ3-o7zWwjNYp6XWWEeHHDfxOzHaHDAWNgJQnVzRGpsqN85KfwsiafMtwCiOjb41ngFBsSkDOktWgztcBhl7r9oOp_RX-V3E0bWr7xv61STFEfqSvnYensbXgubOKs_9OVHmkw8skGlHgzbd_k4q2L_bYlzrdPUIdz-IhB1D8eUKueQzbIDYeouQE7UIHTBT0qbapScGd5AZtO2fzmkbjvRNasuZsk78r8jVrOjCktmwmFW0-XVk-7FE3ByyvqyCWQyqYmSHm5BkwIter3jhMAXLRyC6wPUMWpm7VOA6ceeIDk9Ee30TZryT94CRgXJ_8f26eNReNDIvWF2bhlmHqblwTnPjDKiYCGToEZQ60GhZBkdVP4TLBGSFqJnc3a2N1nFI_PCnT7cAUCwdsWesAU9BHcUCTd268fINMWtKqJmSfBJA6oxD297p8d0KvyU