### get list of programs

GET http://localhost:8000/programs
Content-Type: application/json

### create new program 

POST http://localhost:8000/programs
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxIiwiaWF0IjoxNjYxNzk4MjE2MDA2LCJleHAiOjE2NjE3OTgzMDI0MDZ9.pH4w9GMPyd8-t96iJ8CF3F3D7eU6CYlM5ANLRyMmCqaOgyCFl5AALH07MLfV3HCBf4ktI7nZ8t_HIidLKQHOv_GvwSvh43iLiTgxkf0ilEgCXtEDh-iJO_-kgi2FOmhpCau_umjZYT1HPraQJwESFo_-WbE7tWdqu1uxiGi40_peGuoEt8WAiVIL4Zi1rQ6fpICw22ssu9s7ZQlnjXrNu9mguebSuadwZlnU1z_RkLTCt92bMwM--I5bvT9C6ppzhMbpa7h6WVNTU9vqKOwbbGOts-ODm-wAgey9VZN5Z16VRR2nG10KoxY7fMApZnnJGTvXYGMYrKME0Hgecqyct6V4rS9IarQf8ZlvTer9bFPwfn2gAqLY7iom6z8coMIkzMPK7GU1GmqHcJoiN8XjFd71hc-8L6OyMEqjD1rgWv7yo6Pqfmynw6YkracUdO2tak6x1oSG_k0fnjblGX20iLUKOLAaJFN3gxYjxJCMbpxM-NDZFkLcTtuV8bf4ztEixrSbpEU6hID7j7vDZGSBnx0Rl8AQM-rYMPUbmg8VVJy4e3owpvL0SanaV7CHd8ZyysbhctbEWZOkAP7xEyjL7IWEFHIuDrzSobld_P6YhLTSrmqb2ccuxQzQd3snDizn0Lkx8h_CowtBv2vO1Hmhi8jMrSrk-bMMNXdTYyFugvU
Content-Type: application/json

{
    "name": "novy program"
}

### remove 1 program /programID

DELETE http://localhost:8000/programs/3
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIzIiwiaWF0IjoxNjU4NDE2MjUxODIwLCJleHAiOjE2NTg0MTYzMzgyMjB9.T6CpBX_BDNRVTgl2cRin6Z7a15qIZxYjNeab6tPJBci2aWJlj5RxIkBtgkxHRPXaEYf4o2VEOB3nnNQpdRDlBdONOSoJAzOTLy3VkytCksrV2gkM7TznT84O7hhuP8AhNHyPgwuCuCezBJqMp5K26R60WaQq1MDgEk0N0auD90rEwhZ9O0FtEbTzRgFWaD_haPm7PWXsOFJwxttqsh87rNWQRpXxw5grQcI20j1g38z8Iesk4pGaNzw0mSKZqHxQUNrxf9-MshxWxjNZ1RQmJn8QCGeojWU9szzJ_Y4YLo3BSU2AM9ByXp2P1v5zLbTHKu5m0cRELArMLl4pbcwkKHSXXgsgoC-HMXSg8SKL0vPjZdGLGqPlTmN3BvMDkDbfly4aTc_EQWndvwIeLF9GjoMtB8ec3an7mTWSELDZ6RxC1wEeZUXcNJevZKfHNlI82ERjUfGBYxRZcDuiwRfq2g_xrvOd2zFv9WqRPQzSVKXGZ6eOyfX6Z6CfETnzZn0AY-DpTXf7YV5byF4vS0FF1_TrnAxCKjMuUpp38ucLpUIvGTmY58Xjm37nHW-TwEFxdiwQfFF2t1VYtdFseOeCa4sHQs16sFlmFa4scq3tnkCUGiUy9Vv0TtPpRdHwyMEyexpKtZFmb3Zmu-TXjNT3VCZ5M4QoedBfgE0ZO8i9SHQ

### remove exercise in program /exerciseID/programID

DELETE http://localhost:8000/exercises/10/3
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIzIiwiaWF0IjoxNjU4NDE2MjUxODIwLCJleHAiOjE2NTg0MTYzMzgyMjB9.T6CpBX_BDNRVTgl2cRin6Z7a15qIZxYjNeab6tPJBci2aWJlj5RxIkBtgkxHRPXaEYf4o2VEOB3nnNQpdRDlBdONOSoJAzOTLy3VkytCksrV2gkM7TznT84O7hhuP8AhNHyPgwuCuCezBJqMp5K26R60WaQq1MDgEk0N0auD90rEwhZ9O0FtEbTzRgFWaD_haPm7PWXsOFJwxttqsh87rNWQRpXxw5grQcI20j1g38z8Iesk4pGaNzw0mSKZqHxQUNrxf9-MshxWxjNZ1RQmJn8QCGeojWU9szzJ_Y4YLo3BSU2AM9ByXp2P1v5zLbTHKu5m0cRELArMLl4pbcwkKHSXXgsgoC-HMXSg8SKL0vPjZdGLGqPlTmN3BvMDkDbfly4aTc_EQWndvwIeLF9GjoMtB8ec3an7mTWSELDZ6RxC1wEeZUXcNJevZKfHNlI82ERjUfGBYxRZcDuiwRfq2g_xrvOd2zFv9WqRPQzSVKXGZ6eOyfX6Z6CfETnzZn0AY-DpTXf7YV5byF4vS0FF1_TrnAxCKjMuUpp38ucLpUIvGTmY58Xjm37nHW-TwEFxdiwQfFF2t1VYtdFseOeCa4sHQs16sFlmFa4scq3tnkCUGiUy9Vv0TtPpRdHwyMEyexpKtZFmb3Zmu-TXjNT3VCZ5M4QoedBfgE0ZO8i9SHQ