GET http://localhost:8000/users/allUsers
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIzIiwiaWF0IjoxNjU4NDE3MjY4NTY0LCJleHAiOjE2NTg0MTczNTQ5NjR9.dmukuX-4UhIMPlJjiucW87HnjdGtuCx7V-dSH-8BRPXRsSqvqv-hz2A-71nYgmhJsRyJBzr9Z_d1FtfBYr54MSNT4giBiHtdJdUVOGFH3d44CdA-WS0pg3KgtguD_eUUskBqlHjfiO0W8XduZoJfXIqBsB5gk4CCNxPv5_mcSGUiu5cIqwLOI_BbziU-IukWUbYYUCPqrJmbijWxOs0SuGKCxYD_hVMJGcrVFDYUOgtAYoUkntgztqgrGtSltyr-WOPHAbJH992r8upWUb_F14AAh77p8ARnKPlICsdU76iMcAE2e9E9n7TZrxcplTudil2ctoLaZpOu3gzAd_sPHR8EcPAJfPX6s-RD6E4OFDtWjPZOxjtPBik5k41q5yx2kpXB8TJZBluevtKWLbWyUfchh3c1Dq7kSd4E9FfZWMareQMQGy_7Gwf0mKrn1eD0VsRxs7YUa7JeCisQyOZhKFFKu4BslYjkVt0U-rLUYH62CLutV6efClD-Y2NaYA_bw-pnHP5Bpsi1_B2HodY5n_tljkuoJH7CcLLozIvNEU4uF4ygmviF_rRKp9NK9iodmEiWusy7CPhhQaq5EyhrqF6QiaE5m6WIEndRSlnOxeTbICdCOuXivjJZcXm3WTGahW7XQEwd7Z_B-U5vH1H04XCALctnu8MPfa3ITY0H7Vk

###

GET http://localhost:8000/users/user
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIzIiwiaWF0IjoxNjU4NDM0NDk0NDQ5LCJleHAiOjE2NTg0MzQ1ODA4NDl9.frMOdISTHido2c84xfFCk6E5_ox5fDUpH33Sc7jctL2WKj114379ByQa7GkoKvj431jXzcLZwBcxzDPbFqM1VLc2XBvC3LTSbXRfv9nCZCjN6LxPnS_6JDnHyOjhUgbPNO2dCCu1YwG7xydt1eackelEc3FRxh8S-v8VZ6Yc7IgGpi0XqPk4fgwn5gAyTRgiAkgQQgZKwNm1PRIj0jGHiSRbGp1aTFuYWVUDa7RydzpSvcSOjSpRPUbnp-jsRyNyUu842XfvQdSCjlZPs1H-HiiThmpkTGx1Fr1WEazRmogI2-7iKkxsOgUbZXgUGFXYnPArdtmR4vQl8X-AeGOom7RJ8owCU2JYKPLlpvjVEi4gCQo1DDGywTUjZTQ-w65EewEle-hGHnRXRwiQ7EzD9qqBoapdjIsBASQXO15idN-sVthS4I1Vb5OaKRJv0OH7t-8qf0w6hlONbxKcA0bqC0JPvFIQaFbvmza-iw0sxE_rAWdygNRFzcAu6-oiIAIkbUMsMwQPSthO98I0RjjNYiGVGloPxEcgGpiC3PECbuFBtFydOqTcX4GMhMwmcFcxgYLWEvxxujphoSceM9R-2tRt30wtc5LOPfskkG7SgtAodEbV5--hJuSoah0KbMDjFj69L8HVL3qWQeuyLkGnUDnJU6EZp2j0soAMOqNL1fc

###

GET http://localhost:8000/admin/users
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIzIiwiaWF0IjoxNjU4NzcxNDU4Mzg2LCJleHAiOjE2NTg3NzE1NDQ3ODZ9.jMDfmMvORcFJVwLwF8m7SMmN4mSzQ5aAMYUqikA6nbHHzSHvPWxlmBtuyk9JCNylbQbNao2fM6VcZOY1PL-oAeBmSMBi4kMMYf2sVoOalAFB-GKoRLYuaj8oZyXb71K7urFKgmv3pCljGu4kq-4K7tg0LXXsxrKZjKbq7lPkJx54z-rP4l0QX22olxurVAN1SXUMqwMhEvyEgDAfkR2aEXV3Nl8qaSerajA-mGiMleb1w0WgvrWrAIEPkPXD6nb8O0mg9GVmVw3VzB03s76RxihyxkpxGc7ZPq1LVjcAZL9UG2rTqyz4Rx0b4flgsnao3HARxUM70N0hXMCqWo4vb--8Re_14OhYU9YZdMRZRaX36ptJYEcPT8l3Nwczl_eDU71awH1BL2tQVZdafYGlgHvdX4lSUdy-oCWuKr3l-FjFE8tPNrzmNZ5I5L9vCAtJqkW-__pMW7PRmwZt9sJG-TaMGh9pO40_8JOKhxcpO98wZAdNSOkq9M0NTeYybJUj3D9PBXxqGSBnimLI5iC8BehX-fGTbdDo4oVlM2nA7r3rNiRGGOtFXEBNCgrS-w4f42lgRZXTE4hBCFYJN4djIRzL18F6iQlYb0eV58MgP7Yt-Lj0tEOReqO0QOYXREwrI_l9fVnY_Jqv_ZQxWuOYD4uoCCa1bgj5W0uIJqC4og0

###

GET http://localhost:8000/admin/users/10
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIzIiwiaWF0IjoxNjU4NDE2NzI2NzE2LCJleHAiOjE2NTg0MTY4MTMxMTZ9.O5IPIKNGMCgvCr--GtKZtsfzk_OAwVR0xn7Gp3-zBkqiItWJP2YpgDgGRv8Bg43VVvlt3Szg-oeeGK-cllBGkENrlBY83nR6-fsEygiWGJmqZzAp7QnT4wDu1maka4MAiKs5mDjaCtgPDTkREa2_JrL9VEduXSx0vBkfF9zzKMSMn3JmpfRz2k9JM2NhjIDwYYJkg34iDfe1ZO6xgUwwPorSa39_UajWw2gH-mwag8IBe9dEqPEzHQUFqQh4MA-cuYPBWUe53a9PvE7yl7VRe9Bj_aG1J63fLrEZZ39Qivf-s3E-SzZ_2sEPgHm-46KWtzBkH9ENkgk1-V62AZ7ISnH144JwmRdqYPZWfDHRVw9djPfC7JvUZAnOKjDqJAFXqwmcmspTwxLSXagYtM3gDPlRFy9PahUNv4tQsbqutdaShJf2RPfyOZWvqCRaPnnIVOe3silIQIXz-XUcPi46LVg-0CAQZKrYVXCdWmmrpuAqtg05EI5fhPpr4-knNHPzWEQyUr1hhI7L9ZUA-7f0A1LivM_t9_MfK5Zd9SucmpeqEBKsbrk1lIkzF8LoydrDyp45dwEWzm2LFLeix0a8PchuZD4Nlh3cuAdRy1StMwvMpuGOeIa69V0rD-NRkY9p5iybk9P8IWJ_5kwKZbBRaZyRkQy_j7fG9vdmrb0eS7U

###

PUT http://localhost:8000/admin/users/10
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIzIiwiaWF0IjoxNjU4NDE2OTQ0NDk5LCJleHAiOjE2NTg0MTcwMzA4OTl9.E5sNxgNObz3ZiE7lGg7tRXmTv6nUs6mo160v-nvpThLTv4MZSX7wHyZ-_YNG5CM4rePj900fWHzkh4Ob9xdttzV5FYWFgEvl6A9XZtsLpnscAZ1WnZO7Ni848H6v4oTQbJZV0SXI0RYYAlNem_uBrJLGDcfp0LLa0dwCCgC2ni8lW-6Su6nn8bmG28MCkj6NgthMZpwt0BfqC_foZD42CQSdAEjdB0PbCBizDGfvAXSBCZjdOK92coQCCnCtoZT4D31sbyZbBXGyBJKgmptd2oN-Xf67TG5V-VKwYmgsS0hUmcTRiGSvrppDEboyJzCwYHje3D4FJF4DssS4RKshr6HzyjlWp-lHvsk1-XVvNf3VNsdGBYbCVSKaaGYKIZG4LyFY0x8qgii_Ue5I6Ff4UvLQFTuTtyCoiB3V0FJaNi6wrawrbJPkW9K3cjqQv7dTEnbKkO61LDhI3AlG2S6782H8aICXhTmeLcdkZ-3oqJsqpFtNRotvT6zWOjujijOCo5-fuNo2Z6NVhPccC-6OLtgBEFbanw58DqQp5t_rsbnKkblckiIUO059F93fM_71YP3fF2DL1siflarjlDlxgyiut8R2CR2TPlMBY9dc8GiHGzhyhXktJKwCcESGEahkp6VOk4tcrMjcQT2pf03ta_dK0ahy7c6gQJ6ipfbsdI4
Content-Type: application/json

{
    "name": "q",
    "surname": "q",
    "nickName": "q",
    "age": 33,
}

###

PUT http://localhost:8000/users/1
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxIiwiaWF0IjoxNjYxOTUyODg0Nzg1LCJleHAiOjE2NjE5NTI5NzExODV9.VikUmoFUNXkrv7GH7OhQTuMPgpzlJZR-3ksyMuE_EwzZKtnf9uCbdqkZcFc1aKp7qBfwY4yIpg6kOgzzygRbZkTnc7g1t3fJ8j-wuF-eX9JaCCcE71JYFOT0RLjQDgTaF3PBwNWjK0uqWNykmYA8mJeachXnFT_LNGfMpv9sYQWGxowPkHkevPnBDI84-OtgITLAvhqxgm4R0iGEjP3gmXM83jVKs2BlkSUQNIeY2rBLxZNGKEn384Oh-M34EsWsKBb-UQMKV9Tu8h06oXmSE9QieHZhc2Mb6c1miqLRaKOCzUknUTM2cmKkHD3NC-rZtluUVLFpg1dZbM2np7VCb6KA9lVxNTNbN8lQUOPv19ruHmG3eSL8D5pWp6jX46nx5WbPFIGAyV3ftQ_fBwDFsc7KDNRZeXinCMyIEsUry78JFa2ioSP0nyq6AG3G5OyvQRf-9m5bNm1rVcHL6CJvwNTs3R1LwHBzuXqQCm84TH8ZMdE4cws4fCDid6TfmQ8inyKLagUc-vR3RaTCr33ZFTmWk9NfSUjHGJn_Vyt_YaovgnTp5I0_iJs0DOXrn5NC_ZG_fsH82xTKzKDHq6TmGZAlARzuDwH6NC997DZKBbseeDYFP-1uQL6ZILrcON4mvu-pswx14BDGCYBq4r18zQTPgJXPXvSSvgnWJzFA6F8
Content-Type: application/json

{
    "role": "ADMIN"
}