GET http://localhost:8000/workouts
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxIiwiaWF0IjoxNjY5NTY5MTI0MDQwLCJleHAiOjE2Njk1NjkyMTA0NDB9.QBGPPsuXQ-KOiwlDznxa8wzFJQH1eLZVnsa0kLZlE6bJuoQrUBDQ6ikz24BqJH-leozFaEe_V9tyFTmvXms7xaJQjck18T2e8VbPiUI0FIW91v0X74nxNk21WsT7MKjocubkSITzNPrjjP-R_JidugLv_nyTdFR4MTDlgKzuIdHSNA6y6FdhLmyKEvhMI7E5O7WUHgPqolO-5EVwj16HeDXezzggTn8QFbMF3TVLlyfsQngShEMYPy4ZdQNUe_-O75qakRoeIf0Mjf2OeqdtZCcMtCJ8XvedAv53iTwVbJcvGnvzTKM8IbTg-k1P9z_X8G3izbCxJWP9RGQcgZA0u-EtADPt1hzepEWI3qPnO3HKCOffVTUkzWhbJieQYTM48zxKySsamECv17LfbqjAaOlfvzQe3NAkyj_A06nhV4mFEh1vrEIeN6bkJ4B6GSKmnqPB2Rom-cWZzWyFjvxTlJDf4QXZJPLmurrhpDvAPOHZh3fUqkIrYBVFDZm1qlpWyo3GSQUQizGrzLWHXU5xNj2VnXp6JAVm0WIjPUYkqLjs5t9IesC1Mta9wHHDt1-qvKdt37fFc45J4aczo0_69NrJr9lpmzpeD70GzQrm2ckQfUysuRfROyKPkPd43V9BxXNF7zX3VKQKCGF3vRAdYhu71dfNEHmU9LtGnEKiPTM
Content-Type: application/json

###

POST http://localhost:8000/workouts
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxIiwiaWF0IjoxNjY5NTY5MTI0MDQwLCJleHAiOjE2Njk1NjkyMTA0NDB9.QBGPPsuXQ-KOiwlDznxa8wzFJQH1eLZVnsa0kLZlE6bJuoQrUBDQ6ikz24BqJH-leozFaEe_V9tyFTmvXms7xaJQjck18T2e8VbPiUI0FIW91v0X74nxNk21WsT7MKjocubkSITzNPrjjP-R_JidugLv_nyTdFR4MTDlgKzuIdHSNA6y6FdhLmyKEvhMI7E5O7WUHgPqolO-5EVwj16HeDXezzggTn8QFbMF3TVLlyfsQngShEMYPy4ZdQNUe_-O75qakRoeIf0Mjf2OeqdtZCcMtCJ8XvedAv53iTwVbJcvGnvzTKM8IbTg-k1P9z_X8G3izbCxJWP9RGQcgZA0u-EtADPt1hzepEWI3qPnO3HKCOffVTUkzWhbJieQYTM48zxKySsamECv17LfbqjAaOlfvzQe3NAkyj_A06nhV4mFEh1vrEIeN6bkJ4B6GSKmnqPB2Rom-cWZzWyFjvxTlJDf4QXZJPLmurrhpDvAPOHZh3fUqkIrYBVFDZm1qlpWyo3GSQUQizGrzLWHXU5xNj2VnXp6JAVm0WIjPUYkqLjs5t9IesC1Mta9wHHDt1-qvKdt37fFc45J4aczo0_69NrJr9lpmzpeD70GzQrm2ckQfUysuRfROyKPkPd43V9BxXNF7zX3VKQKCGF3vRAdYhu71dfNEHmU9LtGnEKiPTM
Content-Type: application/json

{
}

###

PUT http://localhost:8000/workouts/1
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxIiwiaWF0IjoxNjY5NTU5MDI3MDg4LCJleHAiOjE2Njk1NTkxMTM0ODh9.T2qkdguxSMUxlRqtJ_mv707Ndq1Epl6Tg012X_SkrVN8SnhsXNE08lNmnd3pnz56d_jdzTYrM9Q6HOr9TooaoGE-UvuTIkWIatRYvPNCCefeLP--z68dTtqhYrrunBqCb4j2FV92l8avV2uQ406O9gqOjNOToOp9xY6XltZuEQdFtSIsypLy4WtHOxJrVzXtStm7rIrAObjMkqCMKygXcIOEey-YGvpm7kGPxpg5AXHhRGYSPVzPwjje62H8AHMsozyHwV4dbnh-xR2AABq2exi9my10BlOjWdFblDnS1oIcPq9S_XGtXR-YFxw6KZoRJ3CCLhe-HIKnE71zZgoVULyW_DnR0PRk8m0f2JhsQIlrssSTVF-nAlrJNgVl6iTwA0YU6DcSq6_PSJQBCLWJf8PQmIiCPZ2TGgCxlf46q8XBnbn6M0recGD3lTqDvdhSP0o61xkfqMVilkpbqp_dEfGCkdB6M76HEdQTLVWt1u2lVEVcOub0QZXtXpE0oI2AfWNYL2vOsAmhqBc5eFslfVw9yA8vHyy59h1FkJU-8Nmmr4bQpdxMvpwQODz18fpenUpQ95xAUZZYnSGUU_KhcIC00jl9IaGg7cZVb5LSbmnUT3AnvbWZoFZr1BmKBfroy-uVninbetou9aOe3oIeTDW4UQxzPWkKzz5bOJ_rtdY
Content-Type: application/json

{
    "name": "monday",
}

###

DELETE http://localhost:8000/workouts/1
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxIiwiaWF0IjoxNjY5NTU5MDI3MDg4LCJleHAiOjE2Njk1NTkxMTM0ODh9.T2qkdguxSMUxlRqtJ_mv707Ndq1Epl6Tg012X_SkrVN8SnhsXNE08lNmnd3pnz56d_jdzTYrM9Q6HOr9TooaoGE-UvuTIkWIatRYvPNCCefeLP--z68dTtqhYrrunBqCb4j2FV92l8avV2uQ406O9gqOjNOToOp9xY6XltZuEQdFtSIsypLy4WtHOxJrVzXtStm7rIrAObjMkqCMKygXcIOEey-YGvpm7kGPxpg5AXHhRGYSPVzPwjje62H8AHMsozyHwV4dbnh-xR2AABq2exi9my10BlOjWdFblDnS1oIcPq9S_XGtXR-YFxw6KZoRJ3CCLhe-HIKnE71zZgoVULyW_DnR0PRk8m0f2JhsQIlrssSTVF-nAlrJNgVl6iTwA0YU6DcSq6_PSJQBCLWJf8PQmIiCPZ2TGgCxlf46q8XBnbn6M0recGD3lTqDvdhSP0o61xkfqMVilkpbqp_dEfGCkdB6M76HEdQTLVWt1u2lVEVcOub0QZXtXpE0oI2AfWNYL2vOsAmhqBc5eFslfVw9yA8vHyy59h1FkJU-8Nmmr4bQpdxMvpwQODz18fpenUpQ95xAUZZYnSGUU_KhcIC00jl9IaGg7cZVb5LSbmnUT3AnvbWZoFZr1BmKBfroy-uVninbetou9aOe3oIeTDW4UQxzPWkKzz5bOJ_rtdY
